demonstrations = [
    {"qid": 240, "context": "If you can check with the other airlines during this period , you may get excellent discount airfare , which may even surprise you .", "question": "How long did it take for them to get excellent discount airfare?", "options": ["4 months", "6 days", "16 minutes", "55 seconds"], "labels": ["no", "no", "yes", "yes"], "cot" : "In order to get excellent discount, the person needs to check with the other airlines. According to commonsense knowledge, it usually takes severay minutes to check with other airlines. Therefore, the answer is C. 16 minutes, D. 55 seconds."},

    {"qid": 319, "context": "We are staying next to the airport which is located next to BARTrail .", "question": "How long did it take for us to stay next to the airport which is located next to BARTrail?", "options": ["1 day", "4 days", "8 decades", "44 minutes"], "labels": ["yes", "yes", "no", "no"], "cot" : "Based on the context, they stay next to the airport located next to BARTrail. According to commonsense knowledge, staying near the airport typically lasts for a few days. Therefore, the answer is A. 1 day, B. 4 days."},

    {"qid": 146, "context": "actually i have an project on it so please give me as much as you have information about migratory birds in punjab", "question": "How long did it take for them to have information about migratory birds in punjab?", "options": ["several months", "12 weeks", "a few minutes", "almost instantly"], "labels": ["no", "no", "yes", "yes"], "cot" : "This is a conversation scenario. In the conversation, providing relevant information about migratory birds in punjab to him is in real-time and takes very little time. Therefore, the answer is C. a few minutes, D. almost instantly."},

    {"qid": 187, "context": "Hope she stops laying eggs because she will get really skinny !", "question": "How long did it take for her to lay eggs?", "options": ["1 week", "22 hours", "2 years", "4 years"], "labels": ["yes", "yes", "no", "no"], "cot" : "According to commonsense knowledge, the time it takes for birds to lay eggs typically varies from one day to several days. Therefore, the answer is A. 1 week, B. 22 hours."}
    
]

demonstrations_cot = demonstrations