demonstrations_cot = [
    {"qid": 100, "context": "A:Hello.Is this room service ?\nB: Yes.May I help you ?\nA: This is room 1425.We asked for the room service an hour ago .\nB: We're very sorry to cause you a lot of inconvenience .\nA: What's the matter ?\nB: We're rather busy right now.It will take <MASK> .\nA: Is it really going to take that long ? Will you rush the order ?\nB: I'm afraid it would take 15 minutes at most .\nA: Ah , well , we have no choice .", "options": ["14 hours ", "another 20 minutes ", "15 seconds ", "another 15 minutes"], "labels": ["no", "yes", "no", "yes"], "cot" : "A wants room service, but B is very busy and needs to wait for a while. Based on commonsense knowledge, the wait time for room service is usually several tens of minutes. Therefore, the answer is B. another 20 minutes, D. another 15 minutes."},

    {"qid": 1300, "context": "A:A guy in my office got the flu the other day . Today I seem to have come down with it , too .\nB: Very likely . You have a slight fever . Do you have a headache , too ?\nA: Yes . I wonder if you could do something to help me recover soon , because I'll be on a business trip in two days .\nB: Well , you have to let your flu run its course . You must stop working and stay in bed to get plenty of rest . Usually it will take <MASK> to make a full recovery .\nA: But I'm going on a business trip in two days !\nB: Maybe you'll have to cancel it or postpone it . If you go out while you are sick , it won't help you recover . You may even pass your disease on to others .\n", "options": ["2 to 3 years", "5 to 7 days", "4 to 6 days", "1 to 2 hours"], "labels": ["no", "yes", "yes", "no"], "cot" : "A may get the flu. Based on commonsense knowledge, it usually takes several days to recover from the flu. Therefore, the answer is B. 5 to 7 days, C. 4 to 6 days."},

    {"qid": 1356, "context": "A:This is today ' s schedule . At 8: 30AM , conference with the department managers . At 9 o ' clock , live for the workshop where you ' ll award prizes to the staff for preventatives .\nB: That ' s great . What are the prizes ?\nA: 3000 RIB as bonus for each person .\nB: To encourage the staff increases .\nA: Ok . Next thing is laying the corner-stone for the new plant at <MASK> . At 12 AM , back here for lunch .\nB: What about the afternoon ?\nA: At 2 PM , give a presentation here with the press . At four o ' clock sharp , have dinner with Mr . Smith , manager of NCC .\n", "options": ["10:00 AM", "2 PM", "8: 30AM", "9:30 AM "], "labels": ["yes", "no", "no", "yes"], "cot" : "According to the dialogue, B will award prizes to the staff at 9:00 AM. Then B will laying the corner-stone for the new plant. At 12:00 AM, B will back here for lunch. The time of laying the corner-stone should be between 9:00 AM and 12:00 AM. Therefore, the answer is A. 10:00 AM, B. 9:30 AM."},

    {"qid": 1344, "context": "A:What schools have you attended ?\nB: I finished Young Primary School in 1998 , and entered Xi ' an Middle School that same September . I graduated from there in <MASK> , and that September I entered Wuhan University , where I'm studying now .\nA: How do you think the education you have received will contribute to your work in this company ?\nB: I think I have a good understanding of fundamentals in the areas your company deals with , and I can go on from here to build up the specific skills and knowledge I need to do my job well .\nA: Your graduation thesis was on Medical Application of Laser , right ? What were your conclusions ?\nB: Yes . I did some work on that , and I found out some really interesting things about the conductivity of liquid helium . I was sure I had a great discovery until my teacher told me the same discovery already made twenty years ago . I think the most important thing , I learnt though , was the importance of keeping good records .\n", "options": ["1998", "July of 2004", "March of 2003", "twenty years ago"], "labels": ["no", "yes", "yes", "no"], "cot" : "Based on the dialogue, B entered middle school in Sep 1998. According to commonsense knowledge, it usually takes around 6 years from entering middle school to graduating from high school (and entering university). Adding 6 years to 1998 would be 2004, so the answer should be around the year 2004. Therefore, the answer is B. July of 2004, C. March of 2003."}   
]

demonstrations = demonstrations_cot