demonstrations = [
    {"Premise": "The other customers fled , and the police said it did not appear that anyone else was injured .", "Hypothesis": "The men took no money from their victim or from the establishment , said Detective Joseph Pentangelo , a Police Department spokesman .", "Label": "BEFORE"},
    {"Premise": "Oil prices have come down from the middle of October from a twenty-two dollar barrel level down to the fourteen dollars we 're seeing today .", "Hypothesis": ".  That 's built up a heck of a momentum and that momentum will look to increase", "Label": "BEFORE"},
    {"Premise": "She also denied accusations made by Amir 's brother , Hagai , that she joined an anti-Arab underground movement .", "Hypothesis": "She said she gave the Amir brothers false information regarding the location of a weapons and ammunition cache when they asked her to help organize such a movement .", "Label": "AFTER", "cot" : "She gave the Amir brothers false information first before she denied accusations made by Amir 's brother, which means Event A occurs after Event B. Therefore, the answer is AFTER."},
    {"Premise": "Iraq said it invaded Kuwait because of disputes over oil and money .", "Hypothesis": "It accused Kuwait of deliberately slashing Iraqi oil revenues by overproducing oil and driving down prices , among other charges .", "Label": "AFTER"}
]

demonstrations_cot = [
    {"Premise": "The other customers fled , and the police said it did not appear that anyone else was injured .", "Hypothesis": "The men took no money from their victim or from the establishment , said Detective Joseph Pentangelo , a Police Department spokesman .", "Label": "BEFORE", "cot" : "The spokeman said after the customers fled, which means Event A occurs before Event B. Therefore, the answer is BEFORE."},    
    {"Premise": "She also denied accusations made by Amir 's brother , Hagai , that she joined an anti-Arab underground movement .", "Hypothesis": "She said she gave the Amir brothers false information regarding the location of a weapons and ammunition cache when they asked her to help organize such a movement .", "Label": "AFTER", "cot" : "She gave the Amir brothers false information first before she denied accusations made by Amir 's brother, which means Event A occurs after Event B. Therefore, the answer is AFTER."},
    {"Premise": "Oil prices have come down from the middle of October from a twenty-two dollar barrel level down to the fourteen dollars we 're seeing today .", "Hypothesis": "That 's built up a heck of a momentum and that momentum will look to increase", "Label": "BEFORE", "cot" : "Oil prices come down lead to momentum, which means Event A occurs before Event B. Therefore, the answer is BEFORE."},
    {"Premise": "Iraq said it invaded Kuwait because of disputes over oil and money .", "Hypothesis": "It accused Kuwait of deliberately slashing Iraqi oil revenues by overproducing oil and driving down prices , among other charges .", "Label": "AFTER", "cot" : "Irqa invaded Kuwait after accusing Kuwait of deliberately slashing Iraqi oil revenues by overproducing oil and driving down prices, which means Event A occurs after Event B. Therefore, the answer is AFTER."}
]