
demonstrations_easy = [
    {"idx": 23, "question": "Who did Evelyn Berezin work for from 1951 to 1969?", "context": "Evelyn Berezin Evelyn Berezin ( April 12 , 1925 \u2013 December 8 , 2018 ) was an American computer designer of the first computer-driven word processor . She also worked on computer-controlled systems for airline reservations . Personal life . Berezin was married for 51 years to Israel Wilenitz , a chemical engineer , born in 1922 in London . Wilenitz died on February 20 , 2003 . Berezin died on December 8 , 2018 , at the age of 93 while in treatment for cancer .", "targets": ["unanswerable"], "question_type": "between_explicit"},
    {"idx": 532, "question": "Which team did Ian Culverhouse play for from 1982 to 1985?", "context": "Ian Culverhouse Ian Brett Culverhouse ( born 22 September 1964 ) is an English former professional footballer and current first-team manager at Kings Lynn Town . He was a defender who played in the position of right-back . Early career . Culverhouse began his career with Tottenham Hotspur . He found first team opportunities limited there and made just two league appearances for the club , though he did get a winners medal in the UEFA Cup as he was an unused substitute for Spurs in the 1984 final against Anderlecht .", "targets": ["Tottenham Hotspur"], "question_type": "between_explicit"},
    {"idx": 1354, "question": "Rosario Crocetta took which position in Nov 2012?", "context": "Rosario Crocetta Rosario Crocetta ( born 8 February 1951 ) is an Italian politician . He was the first openly gay mayor in Italy when he became Mayor of Gela in 2003 , a post he held until 2009 . A prominent figure in the fight against the Mafia , in 2009 he was elected as a Member of the European Parliament ( MEP ) . He was President of Sicily between 2012 and 2017 following the Sicilian regional elections of 2012 , thus becoming the second openly gay head of a regional government in Italy after Nichi Vendola . Personal life . Crocetta is openly gay . He was the first openly gay mayor in Italy when he became Mayor of Gela in 2003 till 2009 . He is also the second openly gay head of a regional government in Italy after Nichi Vendola when he was the President of Sicily between 2012-2017 .", "targets": ["President of Sicily"], "question_type": "in_explicit"},
    {"idx": 156, "question": "Which position did Virginia Bottomley hold in Mar 1992?", "context": "Virginia Bottomley Virginia Hilda Brunette Maxwell Bottomley , Baroness Bottomley of Nettlestone , PC , DL ( n\u00e9e Garnett , born 12 March 1948 ) is a British Conservative Party politician and headhunter . She was a Member of Parliament ( MP ) in the House of Commons from 1984 to 2005 . She was raised to the peerage in 2005 . Retirement . She stepped down from the House of Commons when the 2005 general election was called . On 24 June 2005 she was created a life peer with the title Baroness Bottomley of Nettlestone , of St Helens in the County of Isle of Wight , the parish where she was baptised and celebrated her marriage . She was called to court in 1995 to testify to explain why a bed was not available in a psychiatric unit in Crawley .", "targets": ["Member of Parliament ( MP ) in the House of Commons"], "question_type": "in_explicit"}
]

demonstrations_easy_cot = [
    {"idx": 23, "question": "Who did Evelyn Berezin work for from 1951 to 1969?", "context": "Evelyn Berezin Evelyn Berezin ( April 12 , 1925 \u2013 December 8 , 2018 ) was an American computer designer of the first computer-driven word processor . She also worked on computer-controlled systems for airline reservations . Personal life . Berezin was married for 51 years to Israel Wilenitz , a chemical engineer , born in 1922 in London . Wilenitz died on February 20 , 2003 . Berezin died on December 8 , 2018 , at the age of 93 while in treatment for cancer .", "targets": ["unanswerable"], "question_type": "between_explicit", "cot" : "The context describes Evelyn Berezin's personal life and does not mention her work situation. According to the above facts, it is not possible to determine where she worked from 1951 to 1969, therefore the answer is [unanswerable]."},

    {"idx": 532, "question": "Which team did Ian Culverhouse play for from 1982 to 1985?", "context": "Ian Culverhouse Ian Brett Culverhouse ( born 22 September 1964 ) is an English former professional footballer and current first-team manager at Kings Lynn Town . He was a defender who played in the position of right-back . Early career . Culverhouse began his career with Tottenham Hotspur . He found first team opportunities limited there and made just two league appearances for the club , though he did get a winners medal in the UEFA Cup as he was an unused substitute for Spurs in the 1984 final against Anderlecht .", "targets": ["Tottenham Hotspur"], "question_type": "between_explicit", "cot" : "According to the context, Ian Culverhouse started his professional career in Tottenham Hotspur. In the final match against Anderlecht in 1984, Ian Culverhouse came on as a substitute and won a championship medal for Tottenham Hotspur. According to the aforementioned facts, he played for Tottenham Hotspur between 1982 and 1985, therefore the answer is Tottenham Hotspur."},

    {"idx": 1354, "question": "Rosario Crocetta took which position in Nov 2012?", "context": "Rosario Crocetta Rosario Crocetta ( born 8 February 1951 ) is an Italian politician . He was the first openly gay mayor in Italy when he became Mayor of Gela in 2003 , a post he held until 2009 . A prominent figure in the fight against the Mafia , in 2009 he was elected as a Member of the European Parliament ( MEP ) . He was President of Sicily between 2012 and 2017 following the Sicilian regional elections of 2012 , thus becoming the second openly gay head of a regional government in Italy after Nichi Vendola . Personal life . Crocetta is openly gay . He was the first openly gay mayor in Italy when he became Mayor of Gela in 2003 till 2009 . He is also the second openly gay head of a regional government in Italy after Nichi Vendola when he was the President of Sicily between 2012-2017 .", "targets": ["President of Sicily"], "question_type": "in_explicit", "cot" : "Based to the context, Rosario Crocetta served as the mayor of Gela from 2003 to 2009, and was elected as Member of the European Parliament ( MEP ) in 2009. After the 2012 Sicilian regional elections, he become the President of Sicily from 2012 to 2017. According to the aforementioned facts, he took the position of President of Sicily in November 2012, therefore the answer is President of Sicily."},

    {"idx": 156, "question": "Which position did Virginia Bottomley hold in Mar 1992?", "context": "Virginia Bottomley Virginia Hilda Brunette Maxwell Bottomley , Baroness Bottomley of Nettlestone , PC , DL ( n\u00e9e Garnett , born 12 March 1948 ) is a British Conservative Party politician and headhunter . She was a Member of Parliament ( MP ) in the House of Commons from 1984 to 2005 . She was raised to the peerage in 2005 . Retirement . She stepped down from the House of Commons when the 2005 general election was called . On 24 June 2005 she was created a life peer with the title Baroness Bottomley of Nettlestone , of St Helens in the County of Isle of Wight , the parish where she was baptised and celebrated her marriage . She was called to court in 1995 to testify to explain why a bed was not available in a psychiatric unit in Crawley .", "targets": ["Member of Parliament ( MP ) in the House of Commons"], "question_type": "in_explicit", "cot" : "According to the context, Virginia Bottomley was born in March 1948. She was the Member of Parliament ( MP ) in the House of Commons from 1984 to 2005 and stepped down during the 2005 elections. In June 2005, she was bestowed with the title the title Baroness Bottomley of Nettlestone. In 1995, she was summoned to testify in court. Based on the above facts, her position in March 1992 was Member of Parliament ( MP ) in the House of Commons, therefore the answer is Member of Parliament ( MP ) in the House of Commons."}
]

demonstrations_hard = [
    {"idx": 58, "question": "Who was the head coach of the team FC Cincinnati before Jul 2018?", "context": "FC Cincinnati Football Club Cincinnati , commonly known as FC Cincinnati , is an American professional soccer club based in Cincinnati , Ohio . The club plays in the Eastern Conference of Major League Soccer ( MLS ) . The team succeeded the lower-division team of the same name and was announced on May 29 , 2018 , when MLS awarded an expansion franchise to Cincinnati . The team began MLS play on March 2 , 2019 with its first match against Seattle Sounders FC .On May 29 , 2018 , Major League Soccer announced that Cincinnati would join the league in 2019 as an expansion team under the FC Cincinnati brand . TQL Stadium , a 26,000-seat soccer-specific venue in the West End , is scheduled to open in 2021 . FC Cincinnati signed their first two MLS players , Fanendo Adi and Fatai Alashe , in July 2018 . Adi was the teams first designated player . Both players were loaned to the FC Cincinnati USL team for the remainder of the 2018 season . FC Cincinnati selected five players from certain MLS teams in the expansion draft , which took place on December 11 , 2018 . The players were Darren Mattocks ( D.C United ) , Kei Kamara ( Vancouver Whitecaps FC ) , Roland Lamah ( FC Dallas ) , Eric Alexander ( Houston Dynamo ) , and Hassan Ndam ( New York Red Bulls ) . Kei Kamara was then traded to the Colorado Rapids for an international roster spot . On May 7 , 2019 , the club fired head coach Alan Koch after a 2\u20137\u20132 start to the 2019 MLS season . Assistant coach Yoann Damet was named as interim head coach . President and general manager Jeff Berding cited a culmination of on-field performance and off-field matters for the dismissal . On August 8 , 2019 , Ron Jans was officially hired and made head coach of FC Cincinnati . However , Jans resigned on February 17 , 2020 , amidst an investigation into his alleged use of a racial slur .", "targets": ["Alan Koch"], "question_type": "before_implicit"},

    {"idx": 359, "question": "Theo-Ben Gurirab took which position after Jan 2007?", "context": "Theo-Ben Gurirab Theo-Ben Gurirab ( 23 January 1938 \u2013 14 July 2018 ) was a Namibian politician who served in various senior government positions . He served as the second Prime Minister of Namibia from 28 August 2002 to 20 March 2005 , following the demotion and subsequent resignation of Hage Geingob . Previously he was the countrys first Minister of Foreign Affairs from 1990 to 2002 , and was President of the United Nations General Assembly from 1999 to 2000 . He was Speaker of the National Assembly of Namibia from 2005 to 2015 , when he was replaced by Peter Katjavivi . Gurirab ultimately resigned from politics in 2015 . Death . Gurirab died at a Windhoek hospital on 14 July 2018 of natural causes . He is buried at Heroes Acre .", "targets": ["Speaker of the National Assembly of Namibia"], "question_type": "after_implicit"},

    {"idx": 1168, "question": "Which country did Podolian Governorate belong to in early 1920s?", "context": "Podolian Governorate The Podolia Governorate or Government of Podolia , set up after the Second Partition of Poland , comprised a governorate ( guberniya ) of the Russian Empire from 1793 to 1917 , of the Ukrainian Peoples Republic from 1917 to 1921 , and of the Ukrainian SSR from 1921 to 1925 . Also it was referred after its historical name Podillia . Okruha subdivision . On 12 April 1923 all uyezds ( counties ) were transformed into okruhas ( counties ) , while volosts ( districts ) \u2013 into raions ( districts ) . Okruhas served as a subdivision of government until it was abolished on 1 August 1925 . Together with the government of Podilia , the Haisyn okruha was dissolved as well . Some territory of Tulchyn okruha were included into the newly formed Moldavian Autonomous Soviet Socialist Republic . - Vinnytsia - Haisyn - Kamianets - Mohyliv - Proskuriv - Tulchyn", "targets": ["okruhas"], "question_type": "in_implicit"},

    {"idx": 380, "question": "Marcel de Jong played for which team between Apr 2006 and Nov 2006?", "context": "Marcel de Jong Marcel de Jong ( , ; born 15 October 1986 ) is a Canadian former professional soccer player who played as a left-back . Club career . Early career . De Jong played for amateur side De Valk and joined the PSV Eindhoven youth academy in 1996 . He started his professional career with Dutch Eerste Divisie side Helmond Sport and joined Roda JC in the summer of 2006 .", "targets": ["Roda JC"], "question_type": "between_implicit"}
]

demonstrations_hard_cot = [
    {"idx": 58, "question": "Who was the head coach of the team FC Cincinnati before Jul 2018?", "context": "FC Cincinnati Football Club Cincinnati , commonly known as FC Cincinnati , is an American professional soccer club based in Cincinnati , Ohio . The club plays in the Eastern Conference of Major League Soccer ( MLS ) . The team succeeded the lower-division team of the same name and was announced on May 29 , 2018 , when MLS awarded an expansion franchise to Cincinnati . The team began MLS play on March 2 , 2019 with its first match against Seattle Sounders FC .On May 29 , 2018 , Major League Soccer announced that Cincinnati would join the league in 2019 as an expansion team under the FC Cincinnati brand . TQL Stadium , a 26,000-seat soccer-specific venue in the West End , is scheduled to open in 2021 . FC Cincinnati signed their first two MLS players , Fanendo Adi and Fatai Alashe , in July 2018 . Adi was the teams first designated player . Both players were loaned to the FC Cincinnati USL team for the remainder of the 2018 season . FC Cincinnati selected five players from certain MLS teams in the expansion draft , which took place on December 11 , 2018 . The players were Darren Mattocks ( D.C United ) , Kei Kamara ( Vancouver Whitecaps FC ) , Roland Lamah ( FC Dallas ) , Eric Alexander ( Houston Dynamo ) , and Hassan Ndam ( New York Red Bulls ) . Kei Kamara was then traded to the Colorado Rapids for an international roster spot . On May 7 , 2019 , the club fired head coach Alan Koch after a 2\u20137\u20132 start to the 2019 MLS season . Assistant coach Yoann Damet was named as interim head coach . President and general manager Jeff Berding cited a culmination of on-field performance and off-field matters for the dismissal . On August 8 , 2019 , Ron Jans was officially hired and made head coach of FC Cincinnati . However , Jans resigned on February 17 , 2020 , amidst an investigation into his alleged use of a racial slur .", "targets": ["Alan Koch"], "question_type": "before_implicit", "cot" : "Based on the context, we can summarize the following facts: FC Cincinnati was established in May 2018. In May 2019, the club fired head coach Alan Koch, and assistant coach Yoann Damet was appointed as the interim head coach. In August 2019, Ron Jans was officially hired as the head coach and In February 2020, Ron Jans resigned due to racial slur. According to the aforementioned facts, Alan Koch became the head coach in May 2018 and was fired in May 2019. In June 2018, Alan Koch was still the head coach of the team, therefore the answer is Alan Koch."},

    {"idx": 359, "question": "Theo-Ben Gurirab took which position after Jan 2007?", "context": "Theo-Ben Gurirab Theo-Ben Gurirab ( 23 January 1938 \u2013 14 July 2018 ) was a Namibian politician who served in various senior government positions . He served as the second Prime Minister of Namibia from 28 August 2002 to 20 March 2005 , following the demotion and subsequent resignation of Hage Geingob . Previously he was the countrys first Minister of Foreign Affairs from 1990 to 2002 , and was President of the United Nations General Assembly from 1999 to 2000 . He was Speaker of the National Assembly of Namibia from 2005 to 2015 , when he was replaced by Peter Katjavivi . Gurirab ultimately resigned from politics in 2015 . Death . Gurirab died at a Windhoek hospital on 14 July 2018 of natural causes . He is buried at Heroes Acre .", "targets": ["Speaker of the National Assembly of Namibia"], "question_type": "after_implicit", "cot" : "Based on the context, we can summarize the following facts: Theo-Ben Gurirab served as second Prime Minister of Namibia from August 2002 to March 2005. Prior to that, he was the countrys first Minister of Foreign Affairs from 1990 to 2002 and and was President of the United Nations General Assembly from 1999 to 2000. From 2005 to 2015, he held the position of Speaker of the National Assembly of Namibia. He resigned from politics in 2015 and passed away in July 2018. According to the aforementioned facts, he took the position of Speaker of the National Assembly of Namibia in January 2007, therefore the answer is Speaker of the National Assembly of Namibia."},

    {"idx": 1168, "question": "Which country did Podolian Governorate belong to in early 1920s?", "context": "Podolian Governorate The Podolia Governorate or Government of Podolia , set up after the Second Partition of Poland , comprised a governorate ( guberniya ) of the Russian Empire from 1793 to 1917 , of the Ukrainian Peoples Republic from 1917 to 1921 , and of the Ukrainian SSR from 1921 to 1925 . Also it was referred after its historical name Podillia . Okruha subdivision . On 12 April 1923 all uyezds ( counties ) were transformed into okruhas ( counties ) , while volosts ( districts ) \u2013 into raions ( districts ) . Okruhas served as a subdivision of government until it was abolished on 1 August 1925 . Together with the government of Podilia , the Haisyn okruha was dissolved as well . Some territory of Tulchyn okruha were included into the newly formed Moldavian Autonomous Soviet Socialist Republic . - Vinnytsia - Haisyn - Kamianets - Mohyliv - Proskuriv - Tulchyn", "targets": ["okruhas"], "question_type": "in_implicit", "cot" : "Podolia Governorate comprised a governorate of the Russian Empire from 1793 to 1917, of the Ukrainian Peoples Republic from 1917 to 1921 and of the Ukrainian SSR from 1921 to 1925. On April 1923, all uyezds were transformed into okruhas. Okruhas served as a subdivision of government until it was abolished on August 1925. According to the above facts, Podolia Governorate belongs to Okruhas between April 1923 and August 1925, a period that corresponds to the early 1920s. Therefore, the answer is okruhas."},

    {"idx": 380, "question": "Marcel de Jong played for which team between Apr 2006 and Nov 2006?", "context": "Marcel de Jong Marcel de Jong ( , ; born 15 October 1986 ) is a Canadian former professional soccer player who played as a left-back . Club career . Early career . De Jong played for amateur side De Valk and joined the PSV Eindhoven youth academy in 1996 . He started his professional career with Dutch Eerste Divisie side Helmond Sport and joined Roda JC in the summer of 2006 .", "targets": ["Roda JC"], "question_type": "between_implicit", "cot" : "Marcel de Jong played was born in October 1986. He joined the PSV Eindhoven youth academy in 1996. He joined Roda JC in the summer of 2006. According to the aforementioned facts, he joined Roda JC in the summer of 2006, and the summer of 2006 falls between April and December of 2006, therefore the answer is Roda JC."}
 
]



demonstrations_easy_tot = [
    
]

demonstrations_hard_tot = [

]